name: Build-Docker-Image

on: 
  workflow_dispatch:
  push:
    branches: 
    - main
    - dev
  pull_request:
    branches: 
    - main
    - dev

jobs:
  build_docker_img:
     runs-on: ubuntu-latest
     permissions:
        # required for all workflows
        security-events: write
        # only required for workflows in private repositories
        actions: read
        contents: read
     env:
       TAG: python-api
       VERSION: $(echo $GITHUB_SHA | cut -c1-7)
     
     steps:
     - name: Checkout
       uses: actions/checkout@v3
       
     - name: Build Docker Image
       run: | 
        echo "${{ env.VERSION }}"
        docker build -t $TAG .
        docker tag $TAG ${{ env.TAG }}:${{ env.VERSION }}
        echo "${{ env.TAG }}:${{ env.VERSION }}"
       
       
     - name: Image Scan
       uses: aquasecurity/trivy-action@master
       with:
          image-ref: '${{ env.TAG }}:${{ env.VERSION }}'
          security-checks: 'vuln,secret,config'
          format: 'sarif'
          output: 'trivy-image-results.sarif'
          severity: 'CRITICAL,HIGH'
          
     - name: Upload the scan result to GitHub Security
       uses: github/codeql-action/upload-sarif@v2
       with:
          sarif_file: 'trivy-image-results.sarif'
          category: 'image'
       
